dist: trusty
language: cpp
compiler:
  - g++
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-7
  - export CXX=g++-7
  
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

  # Build main
  - mkdir -p build
  - cd build
  - cmake .. 
  - make